# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        include_format: false
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:
            enabled: true
            force: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
