nelmio_api_doc:
    documentation:
        info:
            title: ToDo application
            description: This is test task
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/task # Accepts routes under /api except /api/doc
